include_recipe(File.expand_path('../../cookbooks/go', __FILE__))
include_recipe(File.expand_path('../../cookbooks/mongodb', __FILE__))
include_recipe(File.expand_path('../../cookbooks/nodejs', __FILE__))
include_recipe(File.expand_path('../../cookbooks/yarn', __FILE__))
include_recipe(File.expand_path('../../cookbooks/gtp5g', __FILE__))
include_recipe(File.expand_path('../../cookbooks/free5gc', __FILE__))
